hamming: lfsr.vhd lossy_channel_tb.vhd lossy_channel.vhd encoder.vhd decoder.vhd
	ghdl -a lfsr.vhd
	ghdl -a encoder.vhd
	ghdl -a decoder.vhd
	ghdl -a lossy_channel.vhd
	ghdl -a lossy_channel_tb.vhd
	ghdl -e lossy_channel_tb